version: '3.5'

services:
  web:
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./src:/src/app/src
      - ./views:/src/app/views
      - ./public:/src/app/public
    env_file:
      - .env-dev
